# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - method: pip
      path: forte/allennlp
    - method: pip
      path: forte/elastic
    - method: pip
      path: forte/faiss
    - method: pip
      path: forte/huggingface
    - method: pip
      path: forte/nltk
    - method: pip
      path: forte/spacy
    - method: pip
      path: forte/stanza
    - method: pip
      path: forte/tweepy
    - method: pip
      path: forte/vader
